<a href="https://colab.research.google.com/github/estefanabermeo/ExtraccionDeDatos/blob/main/Act1_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **ACTIVIDAD 1.1 EXTRACCIÓN DE DATOS**
#### Estefana Bermeo Severiano
#### A01367558

In [60]:
#Importamos librerías requeridas
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [61]:
#Cargar archivo csv desde equipo
#from google.colab import files
#files.upload()

In [62]:
#Carga desde un archivo .xlsx sin indice
df= pd.read_excel('Detalle precios y productos fabricados 2022.xlsx')
df

,CVE_DOC,FECHA_DOC,NOMBRE_VENDEDOR,NOMBRE_CLIENTE,CANT,CVE_ART,DESCR,PRECIO_UNITARIO,COSTO_UNITARIO,COSTO_UNITARIO_CALCULADO,SUBTOTAL_PARTIDA,COSTO_TOTAL_CALCULADO,MARGEN_UNITARIO_CALCULADO,MARGEN_TOTAL_CALCULADO
0,F37034,2022-01-05,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,1,TUE00244,"TUB COBRE 5/16""ØX165MM CIRCULA1.5KW127V",434.48,52.80,52.80,434.48,52.80,381.68,381.68
1,F37036,2022-01-05,LETICIA RAMIREZ HERNANDEZ,JUAN ANTONIO RESENDIZ UGALDE,1,TUA00028,"TUA U"" 5/16 ØX250MM 1200W 120V TAP1""NPT",1264.05,327.18,327.18,1264.05,327.18,936.87,936.87
2,F37041,2022-01-05,DIEGO ARMANDO LEON DURAN,ANA BARBARA CRUZ PALACIOS,7,TP0007,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 7 MT,551.61,177.68,177.68,3861.29,1243.73,373.94,2617.56
3,F37042,2022-01-05,DIEGO ARMANDO LEON DURAN,OMAR RODRIGUEZ GOMEZ,1,TP0001,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 1 MT,140.00,38.96,38.96,140.00,38.96,101.04,101.04
4,F37043,2022-01-05,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,2,BP00242,BAN P INOX 115MMX235MM 1000W 127V T/TOR,172.41,101.71,101.71,344.83,203.42,70.71,141.41
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1421,F39834,2022-12-23,LETICIA RAMIREZ HERNANDEZ,LUIS ENRIQUE PATIÑO PEREZ,6,CS12F1040A00,"CAS INOX 1/2""ØX3"" 400W 127V EXT.30CM",712.00,102.31,102.31,4272.00,613.88,609.69,3658.12
1422,F39834,2022-12-23,LETICIA RAMIREZ HERNANDEZ,LUIS ENRIQUE PATIÑO PEREZ,6,CS12H1050A00,"CAS INOX 1/2""ØX4"" 500W 127V EXT30CM",718.60,104.69,104.69,4311.60,628.12,613.91,3683.48
1423,F39835,2022-12-23,LETICIA RAMIREZ HERNANDEZ,SEVEN DAYS ALL SPORT,3,TUE00394,"TUB INOX 5/16""ØX300MM 5300W 220V ""M"" ESP",2182.35,0.00,596.55,6547.05,1789.64,1585.80,4757.41
1424,F39837,2022-12-23,LETICIA RAMIREZ HERNANDEZ,REVUELTA MONTECARLO,1,TUA00470,"TUB INOX 1/2""ØX500MM 10KW 220V 2 1/2""NPT",5909.84,1884.35,1884.35,5909.84,1884.35,4025.49,4025.49
1425,F39838,2022-12-23,AARON NUÑO CORDOVA,CPEG SOLUTIONS,10,RB00007,FAB BOBINA DSD1 6 COLOCAR B/NUEVA 488V,1406.00,0.00,80.66,14060.00,806.55,1325.34,13253.45

In [63]:
#Verificamos información del DataFrame
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1426 entries, 0 to 1425
Data columns (total 14 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   CVE_DOC                    1426 non-null   object
 1   FECHA_DOC                  1426 non-null   datetime64[ns]
 2   NOMBRE_VENDEDOR            1424 non-null   object
 3   NOMBRE_CLIENTE             1426 non-null   object
 4   CANT                       1426 non-null   int64
 5   CVE_ART                    1426 non-null   object
 6   DESCR                      1426 non-null   object
 7   PRECIO_UNITARIO            1426 non-null   float64
 8   COSTO_UNITARIO             1426 non-null   float64
 9   COSTO_UNITARIO_CALCULADO   1426 non-null   float64
 10  SUBTOTAL_PARTIDA           1426 non-null   float64
 11  COSTO_TOTAL_CALCULADO      1426 non-null   float64
 12  MARGEN_UNITARIO_CALCULADO  1426 non-null   float64
 13  MARGEN_TOTAL_CALCULADO     1426 non-null   float64
dtypes: datetime64[ns](1), float64(7), int64(1), object(5)
memory usage: 156.1+ KB

In [64]:
#Imprimo los primeros 5 registro del dataframe
df.head()

,CVE_DOC,FECHA_DOC,NOMBRE_VENDEDOR,NOMBRE_CLIENTE,CANT,CVE_ART,DESCR,PRECIO_UNITARIO,COSTO_UNITARIO,COSTO_UNITARIO_CALCULADO,SUBTOTAL_PARTIDA,COSTO_TOTAL_CALCULADO,MARGEN_UNITARIO_CALCULADO,MARGEN_TOTAL_CALCULADO
0,F37034,2022-01-05,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,1,TUE00244,"TUB COBRE 5/16""ØX165MM CIRCULA1.5KW127V",434.48,52.80,52.80,434.48,52.80,381.68,381.68
1,F37036,2022-01-05,LETICIA RAMIREZ HERNANDEZ,JUAN ANTONIO RESENDIZ UGALDE,1,TUA00028,"TUA U"" 5/16 ØX250MM 1200W 120V TAP1""NPT",1264.05,327.18,327.18,1264.05,327.18,936.87,936.87
2,F37041,2022-01-05,DIEGO ARMANDO LEON DURAN,ANA BARBARA CRUZ PALACIOS,7,TP0007,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 7 MT,551.61,177.68,177.68,3861.29,1243.73,373.94,2617.56
3,F37042,2022-01-05,DIEGO ARMANDO LEON DURAN,OMAR RODRIGUEZ GOMEZ,1,TP0001,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 1 MT,140.00,38.96,38.96,140.00,38.96,101.04,101.04
4,F37043,2022-01-05,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,2,BP00242,BAN P INOX 115MMX235MM 1000W 127V T/TOR,172.41,101.71,101.71,344.83,203.42,70.71,141.41

1. Filtro por objeto
Las variables filtradas fueron la columna "NOMBRE_VENEDEDOR" pero únicamente las que correspondan a "LETICIA RAMIREZ HERNANDEZ"

In [82]:
# 1. Filtro por objeto
# Las variables filtradas fueron la columna "NOMBRE_VENEDEDOR" pero únicamente las que correspondan a "LETICIA RAMIREZ HERNANDEZ"
filtro1=df[df["NOMBRE_VENDEDOR"] == "LETICIA RAMIREZ HERNANDEZ"]
filtro1

,CVE_DOC,FECHA_DOC,NOMBRE_VENDEDOR,NOMBRE_CLIENTE,CANT,CVE_ART,DESCR,PRECIO_UNITARIO,COSTO_UNITARIO,COSTO_UNITARIO_CALCULADO,SUBTOTAL_PARTIDA,COSTO_TOTAL_CALCULADO,MARGEN_UNITARIO_CALCULADO,MARGEN_TOTAL_CALCULADO
0,F37034,2022-01-05,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,1,TUE00244,"TUB COBRE 5/16""ØX165MM CIRCULA1.5KW127V",434.48,52.80,52.80,434.48,52.80,381.68,381.68
1,F37036,2022-01-05,LETICIA RAMIREZ HERNANDEZ,JUAN ANTONIO RESENDIZ UGALDE,1,TUA00028,"TUA U"" 5/16 ØX250MM 1200W 120V TAP1""NPT",1264.05,327.18,327.18,1264.05,327.18,936.87,936.87
4,F37043,2022-01-05,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,2,BP00242,BAN P INOX 115MMX235MM 1000W 127V T/TOR,172.41,101.71,101.71,344.83,203.42,70.71,141.41
5,F37043,2022-01-05,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,2,BP00243,BAN P INOX 55MMX235MM 450W 127V T/TOR,237.07,49.41,49.41,474.14,98.82,187.66,375.32
7,F37046,2022-01-05,LETICIA RAMIREZ HERNANDEZ,ANA BARBARA CRUZ PALACIOS,3,TP0001,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 1 MT,94.50,38.96,38.96,283.50,116.88,55.54,166.62
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1416,F39830,2022-12-23,LETICIA RAMIREZ HERNANDEZ,TORJJS,3,PJ31Q1G1A400,"TER J 3/16""ØX1/2"" EXT3MT MALLA INOX Z/E",439.15,0.00,123.21,1317.45,369.62,315.94,947.83
1421,F39834,2022-12-23,LETICIA RAMIREZ HERNANDEZ,LUIS ENRIQUE PATIÑO PEREZ,6,CS12F1040A00,"CAS INOX 1/2""ØX3"" 400W 127V EXT.30CM",712.00,102.31,102.31,4272.00,613.88,609.69,3658.12
1422,F39834,2022-12-23,LETICIA RAMIREZ HERNANDEZ,LUIS ENRIQUE PATIÑO PEREZ,6,CS12H1050A00,"CAS INOX 1/2""ØX4"" 500W 127V EXT30CM",718.60,104.69,104.69,4311.60,628.12,613.91,3683.48
1423,F39835,2022-12-23,LETICIA RAMIREZ HERNANDEZ,SEVEN DAYS ALL SPORT,3,TUE00394,"TUB INOX 5/16""ØX300MM 5300W 220V ""M"" ESP",2182.35,0.00,596.55,6547.05,1789.64,1585.80,4757.41
1424,F39837,2022-12-23,LETICIA RAMIREZ HERNANDEZ,REVUELTA MONTECARLO,1,TUA00470,"TUB INOX 1/2""ØX500MM 10KW 220V 2 1/2""NPT",5909.84,1884.35,1884.35,5909.84,1884.35,4025.49,4025.49

In [83]:
# Convertir archivo filtrado a CSV
filtro1.to_csv("filtro1.csv")

In [84]:
# 2. Filtro por filas
# Las variables filtradas fueron todas la columnas pero únicamente las filas 1, 25 y 50
#filtro2= df.iloc[2:15,: ]           #Filas consecutivas
filtro2=df.iloc[ [1, 25, 50] , : ]  #Filas no consecutivas 
filtro2

,CVE_DOC,FECHA_DOC,NOMBRE_VENDEDOR,NOMBRE_CLIENTE,CANT,CVE_ART,DESCR,PRECIO_UNITARIO,COSTO_UNITARIO,COSTO_UNITARIO_CALCULADO,SUBTOTAL_PARTIDA,COSTO_TOTAL_CALCULADO,MARGEN_UNITARIO_CALCULADO,MARGEN_TOTAL_CALCULADO
1,F37036,2022-01-05,LETICIA RAMIREZ HERNANDEZ,JUAN ANTONIO RESENDIZ UGALDE,1,TUA00028,"TUA U"" 5/16 ØX250MM 1200W 120V TAP1""NPT",1264.05,327.18,327.18,1264.05,327.18,936.87,936.87
25,F37071,2022-01-07,DIEGO ARMANDO LEON DURAN,FRANCISCO JAVIER MEDINA SANCHEZ,3,TUA00009,"TUB INOX 7/16""ØX510MM ""U""8000W 440V TAP",1848.00,1081.89,1081.89,5544.00,3245.66,766.11,2298.34
50,F37125,2022-01-17,LETICIA RAMIREZ HERNANDEZ,MANUFACTURAS METALICAS,5,TUS00003,"TUB. INOX. 5/16 Øx615mm. 2000W 440V ""U""""",531.00,85.29,85.29,2655.00,426.47,445.71,2228.53

In [85]:
# Convertir archivo filtrado a CSV
filtro2.to_csv("filtro2.csv")

In [86]:
#3. Filtro por columnas
# Las variables filtradas fueron únicamente las columnas consecutivas de la número 1 a la 5 y todos sus registros
filtro3=df.iloc[ : , 1:5]       #Columnas consecutivas 
#filtro3=df.iloc[ : , [3,5,12]]  #Columnas no consecutivas 
filtro3

      FECHA_DOC            NOMBRE_VENDEDOR                NOMBRE_CLIENTE  CANT
0    2022-01-05  LETICIA RAMIREZ HERNANDEZ            PÚBLICO EN GENERAL     1
1    2022-01-05  LETICIA RAMIREZ HERNANDEZ  JUAN ANTONIO RESENDIZ UGALDE     1
2    2022-01-05   DIEGO ARMANDO LEON DURAN     ANA BARBARA CRUZ PALACIOS     7
3    2022-01-05   DIEGO ARMANDO LEON DURAN          OMAR RODRIGUEZ GOMEZ     1
4    2022-01-05  LETICIA RAMIREZ HERNANDEZ            PÚBLICO EN GENERAL     2
...         ...                        ...                           ...   ...
1421 2022-12-23  LETICIA RAMIREZ HERNANDEZ     LUIS ENRIQUE PATIÑO PEREZ     6
1422 2022-12-23  LETICIA RAMIREZ HERNANDEZ     LUIS ENRIQUE PATIÑO PEREZ     6
1423 2022-12-23  LETICIA RAMIREZ HERNANDEZ          SEVEN DAYS ALL SPORT     3
1424 2022-12-23  LETICIA RAMIREZ HERNANDEZ           REVUELTA MONTECARLO     1
1425 2022-12-23         AARON NUÑO CORDOVA                CPEG SOLUTIONS    10

[1426 rows x 4 columns]

In [87]:
# Convertir archivo filtrado a CSV
filtro3.to_csv("filtro3.csv")

In [68]:
#4. Filtro de filas vs columnas 
#Paso 1: Leemos el contenido del archivo
#from google.colab import files
#uploaded=files.upload()

In [69]:
df1= pd.read_excel('Detalle precios y productos fabricados 2022.xlsx')
df1

,CVE_DOC,FECHA_DOC,NOMBRE_VENDEDOR,NOMBRE_CLIENTE,CANT,CVE_ART,DESCR,PRECIO_UNITARIO,COSTO_UNITARIO,COSTO_UNITARIO_CALCULADO,SUBTOTAL_PARTIDA,COSTO_TOTAL_CALCULADO,MARGEN_UNITARIO_CALCULADO,MARGEN_TOTAL_CALCULADO
0,F37034,2022-01-05,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,1,TUE00244,"TUB COBRE 5/16""ØX165MM CIRCULA1.5KW127V",434.48,52.80,52.80,434.48,52.80,381.68,381.68
1,F37036,2022-01-05,LETICIA RAMIREZ HERNANDEZ,JUAN ANTONIO RESENDIZ UGALDE,1,TUA00028,"TUA U"" 5/16 ØX250MM 1200W 120V TAP1""NPT",1264.05,327.18,327.18,1264.05,327.18,936.87,936.87
2,F37041,2022-01-05,DIEGO ARMANDO LEON DURAN,ANA BARBARA CRUZ PALACIOS,7,TP0007,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 7 MT,551.61,177.68,177.68,3861.29,1243.73,373.94,2617.56
3,F37042,2022-01-05,DIEGO ARMANDO LEON DURAN,OMAR RODRIGUEZ GOMEZ,1,TP0001,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 1 MT,140.00,38.96,38.96,140.00,38.96,101.04,101.04
4,F37043,2022-01-05,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,2,BP00242,BAN P INOX 115MMX235MM 1000W 127V T/TOR,172.41,101.71,101.71,344.83,203.42,70.71,141.41
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1421,F39834,2022-12-23,LETICIA RAMIREZ HERNANDEZ,LUIS ENRIQUE PATIÑO PEREZ,6,CS12F1040A00,"CAS INOX 1/2""ØX3"" 400W 127V EXT.30CM",712.00,102.31,102.31,4272.00,613.88,609.69,3658.12
1422,F39834,2022-12-23,LETICIA RAMIREZ HERNANDEZ,LUIS ENRIQUE PATIÑO PEREZ,6,CS12H1050A00,"CAS INOX 1/2""ØX4"" 500W 127V EXT30CM",718.60,104.69,104.69,4311.60,628.12,613.91,3683.48
1423,F39835,2022-12-23,LETICIA RAMIREZ HERNANDEZ,SEVEN DAYS ALL SPORT,3,TUE00394,"TUB INOX 5/16""ØX300MM 5300W 220V ""M"" ESP",2182.35,0.00,596.55,6547.05,1789.64,1585.80,4757.41
1424,F39837,2022-12-23,LETICIA RAMIREZ HERNANDEZ,REVUELTA MONTECARLO,1,TUA00470,"TUB INOX 1/2""ØX500MM 10KW 220V 2 1/2""NPT",5909.84,1884.35,1884.35,5909.84,1884.35,4025.49,4025.49
1425,F39838,2022-12-23,AARON NUÑO CORDOVA,CPEG SOLUTIONS,10,RB00007,FAB BOBINA DSD1 6 COLOCAR B/NUEVA 488V,1406.00,0.00,80.66,14060.00,806.55,1325.34,13253.45

In [70]:
df1 = df1.set_index('CVE_ART')
df1

,CVE_DOC,FECHA_DOC,NOMBRE_VENDEDOR,NOMBRE_CLIENTE,CANT,DESCR,PRECIO_UNITARIO,COSTO_UNITARIO,COSTO_UNITARIO_CALCULADO,SUBTOTAL_PARTIDA,COSTO_TOTAL_CALCULADO,MARGEN_UNITARIO_CALCULADO,MARGEN_TOTAL_CALCULADO
CVE_ART,,,,,,,,,,,,,
TUE00244,F37034,2022-01-05,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,1,"TUB COBRE 5/16""ØX165MM CIRCULA1.5KW127V",434.48,52.80,52.80,434.48,52.80,381.68,381.68
TUA00028,F37036,2022-01-05,LETICIA RAMIREZ HERNANDEZ,JUAN ANTONIO RESENDIZ UGALDE,1,"TUA U"" 5/16 ØX250MM 1200W 120V TAP1""NPT",1264.05,327.18,327.18,1264.05,327.18,936.87,936.87
TP0007,F37041,2022-01-05,DIEGO ARMANDO LEON DURAN,ANA BARBARA CRUZ PALACIOS,7,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 7 MT,551.61,177.68,177.68,3861.29,1243.73,373.94,2617.56
TP0001,F37042,2022-01-05,DIEGO ARMANDO LEON DURAN,OMAR RODRIGUEZ GOMEZ,1,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 1 MT,140.00,38.96,38.96,140.00,38.96,101.04,101.04
BP00242,F37043,2022-01-05,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,2,BAN P INOX 115MMX235MM 1000W 127V T/TOR,172.41,101.71,101.71,344.83,203.42,70.71,141.41
...,...,...,...,...,...,...,...,...,...,...,...,...,...
CS12F1040A00,F39834,2022-12-23,LETICIA RAMIREZ HERNANDEZ,LUIS ENRIQUE PATIÑO PEREZ,6,"CAS INOX 1/2""ØX3"" 400W 127V EXT.30CM",712.00,102.31,102.31,4272.00,613.88,609.69,3658.12
CS12H1050A00,F39834,2022-12-23,LETICIA RAMIREZ HERNANDEZ,LUIS ENRIQUE PATIÑO PEREZ,6,"CAS INOX 1/2""ØX4"" 500W 127V EXT30CM",718.60,104.69,104.69,4311.60,628.12,613.91,3683.48
TUE00394,F39835,2022-12-23,LETICIA RAMIREZ HERNANDEZ,SEVEN DAYS ALL SPORT,3,"TUB INOX 5/16""ØX300MM 5300W 220V ""M"" ESP",2182.35,0.00,596.55,6547.05,1789.64,1585.80,4757.41
TUA00470,F39837,2022-12-23,LETICIA RAMIREZ HERNANDEZ,REVUELTA MONTECARLO,1,"TUB INOX 1/2""ØX500MM 10KW 220V 2 1/2""NPT",5909.84,1884.35,1884.35,5909.84,1884.35,4025.49,4025.49
RB00007,F39838,2022-12-23,AARON NUÑO CORDOVA,CPEG SOLUTIONS,10,FAB BOBINA DSD1 6 COLOCAR B/NUEVA 488V,1406.00,0.00,80.66,14060.00,806.55,1325.34,13253.45

In [88]:
#Paso 2: Aplicamos Filtro de filas vs columnas 
# Las variables filtradas fueron el ínidce CVE_ART (sólo aquellos registros con valor "TUE00244" y "RB00007") y el PRECIO_UNITARIO
filtro4=df1.loc[["TUE00244","RB00007"], ["PRECIO_UNITARIO"]]
filtro4

          PRECIO_UNITARIO
CVE_ART
TUE00244           434.48
RB00007           1897.27
RB00007           1406.00

In [89]:
# Convertir archivo filtrado a CSV
filtro4.to_csv("filtro4.csv")

In [90]:
# 5. Filtro por cabecera
# El filtro se aplicó a los primeros 5 registros de todas las columnas/variables
filtro5 = df.head(5)
filtro5

,CVE_DOC,FECHA_DOC,NOMBRE_VENDEDOR,NOMBRE_CLIENTE,CANT,CVE_ART,DESCR,PRECIO_UNITARIO,COSTO_UNITARIO,COSTO_UNITARIO_CALCULADO,SUBTOTAL_PARTIDA,COSTO_TOTAL_CALCULADO,MARGEN_UNITARIO_CALCULADO,MARGEN_TOTAL_CALCULADO
0,F37034,2022-01-05,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,1,TUE00244,"TUB COBRE 5/16""ØX165MM CIRCULA1.5KW127V",434.48,52.80,52.80,434.48,52.80,381.68,381.68
1,F37036,2022-01-05,LETICIA RAMIREZ HERNANDEZ,JUAN ANTONIO RESENDIZ UGALDE,1,TUA00028,"TUA U"" 5/16 ØX250MM 1200W 120V TAP1""NPT",1264.05,327.18,327.18,1264.05,327.18,936.87,936.87
2,F37041,2022-01-05,DIEGO ARMANDO LEON DURAN,ANA BARBARA CRUZ PALACIOS,7,TP0007,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 7 MT,551.61,177.68,177.68,3861.29,1243.73,373.94,2617.56
3,F37042,2022-01-05,DIEGO ARMANDO LEON DURAN,OMAR RODRIGUEZ GOMEZ,1,TP0001,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 1 MT,140.00,38.96,38.96,140.00,38.96,101.04,101.04
4,F37043,2022-01-05,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,2,BP00242,BAN P INOX 115MMX235MM 1000W 127V T/TOR,172.41,101.71,101.71,344.83,203.42,70.71,141.41

In [91]:
# Convertir archivo filtrado a CSV
filtro5.to_csv("filtro5.csv")

**FILTROS BASICOS PARA VARIABLES CUANTITATIVAS**

In [92]:
# 6. Filtro por comparacion
# El filtro se aplicó a la variable "PRECIO_UNITARIO" para aquellos registros con valor superior a 10,000
filtro6 = df[df["PRECIO_UNITARIO"] > 10000]
filtro6

,CVE_DOC,FECHA_DOC,NOMBRE_VENDEDOR,NOMBRE_CLIENTE,CANT,CVE_ART,DESCR,PRECIO_UNITARIO,COSTO_UNITARIO,COSTO_UNITARIO_CALCULADO,SUBTOTAL_PARTIDA,COSTO_TOTAL_CALCULADO,MARGEN_UNITARIO_CALCULADO,MARGEN_TOTAL_CALCULADO
6,F37044,2022-01-05,DIEGO ARMANDO LEON DURAN,AIRBUS HELICOPTERS MEXICO QUERETARO,1,RP00165,REPARACION DE BATIDOR 16.6KW 440V,14000.00,5323.76,5323.76,14000.00,5323.76,8676.24,8676.24
40,F37102,2022-01-12,ALFREDO CANELA,DEACERO,3,TUE00321,"TUB INOX 1/2""ØX1030MMX980MM 3KW480V ""L""",12720.00,0.00,1509.14,38160.00,4527.42,11210.86,33632.58
347,F37697,2022-03-23,DIEGO ARMANDO LEON DURAN,AIRBUS HELICOPTERS MEXICO QUERETARO,1,RP00165,REPARACION DE BATIDOR 16.6KW 440V,14000.00,5211.65,5211.65,14000.00,5211.65,8788.35,8788.35
373,F37734,2022-03-28,DIEGO ARMANDO LEON DURAN,DIECASTING CELAYA,2,BO00005,BO ABIERTA ALAMBRE CAL. 6 40 KW 440 V,18500.00,0.00,1560.44,37000.00,3120.88,16939.56,33879.12
419,F37817,2022-03-31,ALFREDO CANELA,FABRICACION Y MONTAJE DE EQUIPO INDUSTRIAL,1,GAB00014,GABINETE ELECTRICO DE 50X40X20 70KW 440V,20887.18,0.00,1516.24,20887.18,1516.24,19370.94,19370.94
479,F37933,2022-04-20,LETICIA RAMIREZ HERNANDEZ,JUAN CARLOS HERNANDEZ PEREZ,1,TUE00172,"TUB INOX 1/2""ØX670MM 22.5W480V BRIDA 6""",23995.24,4045.07,4045.07,23995.24,4045.07,19950.17,19950.17
558,F38097,2022-05-06,ALFREDO CANELA,PAS APPLIANCE SYSTEMS,2,EE00021,FABRICACION DE CRISOL 500W 127V 50-60HZ,13800.00,2227.85,2227.85,27600.00,4455.70,11572.15,23144.30
588,F38160,2022-05-13,ALFREDO CANELA,COLEP,1,RP00196,REPARACION EQUIPO COCINA 5000W 22OV,13776.88,0.00,5301.49,13776.88,5301.49,8475.39,8475.39
655,F38315,2022-06-06,AARON NUÑO CORDOVA,MEGO AFEK,1,TUA00325,"TUB INOX 1/2""ØX75CM ""U"" 30KW440V BRIDA6""",12500.00,3900.52,3900.52,12500.00,3900.52,8599.48,8599.48
672,F38352,2022-06-10,ALFREDO CANELA,FLEX-N-GATE MEXICO,1,RP00203,REPARACION HORNO 15KW 440V TOTAL,32582.18,0.00,199335.56,32582.18,199335.56,-166753.38,-166753.38
842,F38648,2022-07-22,LETICIA RAMIREZ HERNANDEZ,JUAN CARLOS HERNANDEZ PEREZ,1,TUE00172,"TUB INOX 1/2""ØX670MM 22.5W480V BRIDA 6""",25258.15,5169.85,5169.85,25258.15,5169.85,20088.30,20088.30
851,F38665,2022-07-26,DIEGO ARMANDO LEON DURAN,AIRBUS HELICOPTERS MEXICO QUERETARO,1,RP00165,REPARACION DE BATIDOR 16.6KW 440V,14000.00,0.00,277.50,14000.00,277.50,13722.50,13722.50
866,F38705,2022-07-29,ALFREDO CANELA,KERN LIEBERS MEXICO,1,EE00063,FABRICACIÓN ESPECIAL 1300W 115V,18869.00,0.00,1721.28,18869.00,1721.28,17147.72,17147.72
931,F38850,2022-08-18,LETICIA RAMIREZ HERNANDEZ,JUAN CARLOS HERNANDEZ PEREZ,1,TUE00172,"TUB INOX 1/2""ØX670MM 22.5W480V BRIDA 6""",25258.15,2754.67,2754.67,25258.15,2754.67,22503.48,22503.48
960,F38910,2022-08-25,ALFREDO CANELA,RICHALUM,2,BOBINA004,RESIST TIPO BOBINA CAL. 6 DSD 30 KW 440V,18482.78,2613.60,2613.60,36965.56,5227.20,15869.18,31738.36
1046,F39088,2022-09-20,LETICIA RAMIREZ HERNANDEZ,EDGAR GARCIA HERNANDEZ,1,TUE00378,"TUB INOX 1/2""ØX746MM 30KW 440V ""U"" BRI8""",22417.60,0.00,9353.62,22417.60,9353.62,13063.98,13063.98
1101,F39191,2022-09-30,LETICIA RAMIREZ HERNANDEZ,CAROLINA PEREZ GOMEZ,2,TUE00382,"TUB INOX 1/2""ØX80CM 80KW 440V ""U"" PLAC",17393.06,0.00,6073.50,34786.12,12146.99,11319.56,22639.13
1104,F39201,2022-09-30,ALFREDO CANELA,KERN LIEBERS MEXICO,4,EE00063,FABRICACIÓN ESPECIAL 1300W 115V,18869.00,0.00,1721.28,75476.00,6885.12,17147.72,68590.88
1226,F39436,2022-10-28,ALFREDO CANELA,KERN LIEBERS MEXICO,4,EE00063,FABRICACIÓN ESPECIAL 1300W 115V,18869.00,1721.28,1721.28,75476.00,6885.12,17147.72,68590.88
1253,F39503,2022-11-04,ALFREDO CANELA,CENTRO DE INVESTIGACION Y DESARROLLO TECNOLOGI...,1,RP00192,REPARACION DE HORNO LINDBERG/BLUE M,17450.00,0.20,0.20,17450.00,0.20,17449.80,17449.80
1277,F39560,2022-11-11,ALFREDO CANELA,MEGO AFEK,2,TUA00325,"TUB INOX 1/2""ØX75CM ""U"" 30KW440V BRIDA6""",12500.00,0.00,4604.19,25000.00,9208.38,7895.81,15791.62
1288,F39576,2022-11-15,ALFREDO CANELA,CARCOUSTICS INDUSTRIAL DE MEXICO,1,EE00022,PLACAS DE FIBRA CERAMICA BARRENADAS,27808.00,0.00,654.34,27808.00,654.34,27153.66,27153.66
1296,F39592,2022-11-16,DIEGO ARMANDO LEON DURAN,AIRBUS HELICOPTERS MEXICO QUERETARO,1,RP00165,REPARACION DE BATIDOR 16.6KW 440V,14000.00,0.00,277.50,14000.00,277.50,13722.50,13722.50
1355,F39696,2022-12-05,ALFREDO CANELA,SIKA MEXICANA,1,RP00229,REPARACION DE HORNO 1500W 127V,13688.00,0.00,0.00,13688.00,0.00,13688.00,13688.00
1360,F39716,2022-12-07,ALFREDO CANELA,DIECASTING CELAYA,1,BO00005,BO ABIERTA ALAMBRE CAL. 6 40 KW 440 V,18482.78,1734.88,1734.88,18482.78,1734.88,16747.90,16747.90
1393,F39788,2022-12-19,ALFREDO CANELA,WHITEHALL INDUSTRIES DE MEXICO,1,TUA00494,"TUB INOX 7/16""ØX105CM 24KW 480V 3PZ",11809.98,0.00,2335.20,11809.98,2335.20,9474.78,9474.78
1412,F39824,2022-12-23,ALFREDO CANELA,MEGO AFEK,1,TUA00325,"TUB INOX 1/2""ØX75CM ""U"" 30KW440V BRIDA6""",12500.00,4579.08,4579.08,12500.00,4579.08,7920.92,7920.92

In [93]:
# Convertir archivo filtrado a CSV
filtro6.to_csv("filtro6.csv")

**FILTROS BASICOS CON CONETORES LOGICOS**

In [94]:
# 7. Filtro Y
# El filtro se aplicó a las variables PRECIO_UNITARIO menor a 8,000 y a la FECHA_DOC correspondiente al 5 de enero 2022
filtro7=df[(df["PRECIO_UNITARIO"] < 8000) & (df["FECHA_DOC"] == "2022-01-05")]
filtro7

,CVE_DOC,FECHA_DOC,NOMBRE_VENDEDOR,NOMBRE_CLIENTE,CANT,CVE_ART,DESCR,PRECIO_UNITARIO,COSTO_UNITARIO,COSTO_UNITARIO_CALCULADO,SUBTOTAL_PARTIDA,COSTO_TOTAL_CALCULADO,MARGEN_UNITARIO_CALCULADO,MARGEN_TOTAL_CALCULADO
0,F37034,2022-01-05,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,1,TUE00244,"TUB COBRE 5/16""ØX165MM CIRCULA1.5KW127V",434.48,52.80,52.80,434.48,52.80,381.68,381.68
1,F37036,2022-01-05,LETICIA RAMIREZ HERNANDEZ,JUAN ANTONIO RESENDIZ UGALDE,1,TUA00028,"TUA U"" 5/16 ØX250MM 1200W 120V TAP1""NPT",1264.05,327.18,327.18,1264.05,327.18,936.87,936.87
2,F37041,2022-01-05,DIEGO ARMANDO LEON DURAN,ANA BARBARA CRUZ PALACIOS,7,TP0007,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 7 MT,551.61,177.68,177.68,3861.29,1243.73,373.94,2617.56
3,F37042,2022-01-05,DIEGO ARMANDO LEON DURAN,OMAR RODRIGUEZ GOMEZ,1,TP0001,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 1 MT,140.00,38.96,38.96,140.00,38.96,101.04,101.04
4,F37043,2022-01-05,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,2,BP00242,BAN P INOX 115MMX235MM 1000W 127V T/TOR,172.41,101.71,101.71,344.83,203.42,70.71,141.41
5,F37043,2022-01-05,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,2,BP00243,BAN P INOX 55MMX235MM 450W 127V T/TOR,237.07,49.41,49.41,474.14,98.82,187.66,375.32
7,F37046,2022-01-05,LETICIA RAMIREZ HERNANDEZ,ANA BARBARA CRUZ PALACIOS,3,TP0001,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 1 MT,94.50,38.96,38.96,283.50,116.88,55.54,166.62
8,F37048,2022-01-05,DIEGO ARMANDO LEON DURAN,FIDEICOMISO F/1596,1,TUE00207,"TUB INCOLOY 1/2""Øx412mm J 9KW 240V PLACA",1615.00,517.89,517.89,1615.00,517.89,1097.11,1097.11
9,F37049,2022-01-05,DIEGO ARMANDO LEON DURAN,FIDEICOMISO F/1596,1,TUE00207,"TUB INCOLOY 1/2""Øx412mm J 9KW 240V PLACA",1615.00,517.89,517.89,1615.00,517.89,1097.11,1097.11
10,F37050,2022-01-05,DIEGO ARMANDO LEON DURAN,FIDEICOMISO F/1596,1,TUE00207,"TUB INCOLOY 1/2""Øx412mm J 9KW 240V PLACA",1615.00,517.89,517.89,1615.00,517.89,1097.11,1097.11
11,F37051,2022-01-05,DIEGO ARMANDO LEON DURAN,FIDEICOMISO F/1596,1,TUE00207,"TUB INCOLOY 1/2""Øx412mm J 9KW 240V PLACA",1615.00,0.00,586.32,1615.00,586.32,1028.68,1028.68
12,F37052,2022-01-05,DIEGO ARMANDO LEON DURAN,FIDEICOMISO F/1596,1,TUE00207,"TUB INCOLOY 1/2""Øx412mm J 9KW 240V PLACA",1615.00,0.00,586.32,1615.00,586.32,1028.68,1028.68
13,F37053,2022-01-05,DIEGO ARMANDO LEON DURAN,SANDIBEEL BECERRA HURTADO,1,BO00051,BOB 8020 CAL.26 127V BAS28.5CMX27CM MICA,1485.25,0.00,86.22,1485.25,86.22,1399.03,1399.03
14,F37054,2022-01-05,DIEGO ARMANDO LEON DURAN,INDUSTRIAS NIBA,1,BC00023,BC INOX 114MMØX165MM 1500W 230V C/ALLEN,2095.25,0.00,742.05,2095.25,742.05,1353.20,1353.20
15,F37058,2022-01-05,DIEGO ARMANDO LEON DURAN,MOLINERA DE MEXICO,5,PT00070,"PT-100 1/8""ØX30MM EXT 1.5MT 3HILOS Z/ESP",192.50,51.73,149.60,481.25,397.08,42.90,84.17
16,F37059,2022-01-05,DIEGO ARMANDO LEON DURAN,SILCA CERAMICO PRODUCTOS,2,TP0011,"TERMOPAR CERAMICO T/K"" LONG 12"" CAL 8""",771.28,124.00,124.00,1542.56,248.00,647.28,1294.56
17,F37060,2022-01-05,DIEGO ARMANDO LEON DURAN,OSCAR VALDEZ GUADARRAMA,3,PJ31C1F1AA00,"TER J 3/16""ØX2"" EXT.2MT CON-1/2"" NPT",125.00,0.00,141.90,375.00,425.69,-16.90,-50.69
18,F37061,2022-01-05,ALFREDO CANELA,ELICAMEX,5,WRE-2133,BAN MICA 120mmØx50mm 850W 440V TTORNILLO,821.30,0.00,78.70,4106.50,393.48,742.60,3713.02
19,F37061,2022-01-05,ALFREDO CANELA,ELICAMEX,7,WRE-2774,BAN MICA Ø120MM X 50 MM 700W 440V T TOR,821.30,0.00,75.77,5749.10,530.41,745.53,5218.69
20,F37061,2022-01-05,ALFREDO CANELA,ELICAMEX,3,WRE-4885,BAN INOX 36MMØX25MM 150W 240V EXT30CM,496.35,27.43,27.43,1489.05,82.29,468.92,1406.76

In [95]:
# Convertir archivo filtrado a CSV
filtro7.to_csv("filtro7.csv")

In [96]:
# 8. Filtro o
# El filtro se aplicó a las variables PRECIO_UNITARIO menor a 8,000 ó a la FECHA_DOC correspondiente al 5 de enero 2022
filtro8=df[(df["PRECIO_UNITARIO"] < 8000) | (df["FECHA_DOC"] == "2022-01-05")]
filtro8

,CVE_DOC,FECHA_DOC,NOMBRE_VENDEDOR,NOMBRE_CLIENTE,CANT,CVE_ART,DESCR,PRECIO_UNITARIO,COSTO_UNITARIO,COSTO_UNITARIO_CALCULADO,SUBTOTAL_PARTIDA,COSTO_TOTAL_CALCULADO,MARGEN_UNITARIO_CALCULADO,MARGEN_TOTAL_CALCULADO
0,F37034,2022-01-05,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,1,TUE00244,"TUB COBRE 5/16""ØX165MM CIRCULA1.5KW127V",434.48,52.80,52.80,434.48,52.80,381.68,381.68
1,F37036,2022-01-05,LETICIA RAMIREZ HERNANDEZ,JUAN ANTONIO RESENDIZ UGALDE,1,TUA00028,"TUA U"" 5/16 ØX250MM 1200W 120V TAP1""NPT",1264.05,327.18,327.18,1264.05,327.18,936.87,936.87
2,F37041,2022-01-05,DIEGO ARMANDO LEON DURAN,ANA BARBARA CRUZ PALACIOS,7,TP0007,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 7 MT,551.61,177.68,177.68,3861.29,1243.73,373.94,2617.56
3,F37042,2022-01-05,DIEGO ARMANDO LEON DURAN,OMAR RODRIGUEZ GOMEZ,1,TP0001,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 1 MT,140.00,38.96,38.96,140.00,38.96,101.04,101.04
4,F37043,2022-01-05,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,2,BP00242,BAN P INOX 115MMX235MM 1000W 127V T/TOR,172.41,101.71,101.71,344.83,203.42,70.71,141.41
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1421,F39834,2022-12-23,LETICIA RAMIREZ HERNANDEZ,LUIS ENRIQUE PATIÑO PEREZ,6,CS12F1040A00,"CAS INOX 1/2""ØX3"" 400W 127V EXT.30CM",712.00,102.31,102.31,4272.00,613.88,609.69,3658.12
1422,F39834,2022-12-23,LETICIA RAMIREZ HERNANDEZ,LUIS ENRIQUE PATIÑO PEREZ,6,CS12H1050A00,"CAS INOX 1/2""ØX4"" 500W 127V EXT30CM",718.60,104.69,104.69,4311.60,628.12,613.91,3683.48
1423,F39835,2022-12-23,LETICIA RAMIREZ HERNANDEZ,SEVEN DAYS ALL SPORT,3,TUE00394,"TUB INOX 5/16""ØX300MM 5300W 220V ""M"" ESP",2182.35,0.00,596.55,6547.05,1789.64,1585.80,4757.41
1424,F39837,2022-12-23,LETICIA RAMIREZ HERNANDEZ,REVUELTA MONTECARLO,1,TUA00470,"TUB INOX 1/2""ØX500MM 10KW 220V 2 1/2""NPT",5909.84,1884.35,1884.35,5909.84,1884.35,4025.49,4025.49
1425,F39838,2022-12-23,AARON NUÑO CORDOVA,CPEG SOLUTIONS,10,RB00007,FAB BOBINA DSD1 6 COLOCAR B/NUEVA 488V,1406.00,0.00,80.66,14060.00,806.55,1325.34,13253.45

In [98]:
# Convertir archivo filtrado a CSV
filtro8.to_csv("filtro8.csv")

In [99]:
# 9. Filtro not
# El filtro se aplicó a todas las variables excepto al PRECIO_UNITARIO mayor o igual a 8,000 y tampoco a la FECHA_DOC correspondiente al 5 de enero 2022
filtro9=df[~(df["PRECIO_UNITARIO"] >= 8000) & ~(df["FECHA_DOC"] == "2022-01-05")]
filtro9

,CVE_DOC,FECHA_DOC,NOMBRE_VENDEDOR,NOMBRE_CLIENTE,CANT,CVE_ART,DESCR,PRECIO_UNITARIO,COSTO_UNITARIO,COSTO_UNITARIO_CALCULADO,SUBTOTAL_PARTIDA,COSTO_TOTAL_CALCULADO,MARGEN_UNITARIO_CALCULADO,MARGEN_TOTAL_CALCULADO
21,F37067,2022-01-07,DIEGO ARMANDO LEON DURAN,APEX TOOL GROUP MANUFACTURING MEXICO,3,MR01934,"PT-100 3/16""ØX11/2"" EXT3MTS TEFLON Z-PIN",938.53,147.76,147.76,2815.59,443.27,790.77,2372.32
22,F37068,2022-01-07,DIEGO ARMANDO LEON DURAN,KWANTREATS,1,PT00080,PT-100 4MMØX10CM EXT 5MT TEFLON 2HILOS,718.52,259.35,259.35,718.52,259.35,459.17,459.17
23,F37068,2022-01-07,DIEGO ARMANDO LEON DURAN,KWANTREATS,1,PT00081,"PT-100 DE 1/4""ØX14.5CM EXT 5MT CONECTOR",898.25,332.65,332.65,898.25,332.65,565.60,565.60
24,F37069,2022-01-07,AARON NUÑO CORDOVA,ADVANEX DE MEXICO,2,RP00150,REPARACION DE TERMOPAR,1500.00,0.36,0.36,3000.00,0.72,1499.64,2999.28
25,F37071,2022-01-07,DIEGO ARMANDO LEON DURAN,FRANCISCO JAVIER MEDINA SANCHEZ,3,TUA00009,"TUB INOX 7/16""ØX510MM ""U""8000W 440V TAP",1848.00,1081.89,1081.89,5544.00,3245.66,766.11,2298.34
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1421,F39834,2022-12-23,LETICIA RAMIREZ HERNANDEZ,LUIS ENRIQUE PATIÑO PEREZ,6,CS12F1040A00,"CAS INOX 1/2""ØX3"" 400W 127V EXT.30CM",712.00,102.31,102.31,4272.00,613.88,609.69,3658.12
1422,F39834,2022-12-23,LETICIA RAMIREZ HERNANDEZ,LUIS ENRIQUE PATIÑO PEREZ,6,CS12H1050A00,"CAS INOX 1/2""ØX4"" 500W 127V EXT30CM",718.60,104.69,104.69,4311.60,628.12,613.91,3683.48
1423,F39835,2022-12-23,LETICIA RAMIREZ HERNANDEZ,SEVEN DAYS ALL SPORT,3,TUE00394,"TUB INOX 5/16""ØX300MM 5300W 220V ""M"" ESP",2182.35,0.00,596.55,6547.05,1789.64,1585.80,4757.41
1424,F39837,2022-12-23,LETICIA RAMIREZ HERNANDEZ,REVUELTA MONTECARLO,1,TUA00470,"TUB INOX 1/2""ØX500MM 10KW 220V 2 1/2""NPT",5909.84,1884.35,1884.35,5909.84,1884.35,4025.49,4025.49
1425,F39838,2022-12-23,AARON NUÑO CORDOVA,CPEG SOLUTIONS,10,RB00007,FAB BOBINA DSD1 6 COLOCAR B/NUEVA 488V,1406.00,0.00,80.66,14060.00,806.55,1325.34,13253.45

In [100]:
# Convertir archivo filtrado a CSV
filtro9.to_csv("filtro9.csv")